### ISSUE TITLE
ゲージ増加時に光らせる・減少する時に揺らす

### ISSUE THREAD

**Issue by asterisk-cn** [asterisk-cn/BSGJ-E1#113]

**Comment by asterisk-cn** [comment]
被ダメージ時　合体ゲージを振動
ゲージマックス時　腕と炎を点灯

**Comment by Iguchi-Keigo2000** [comment]
魂被ダメージ時の合体ゲージの振動とゲージマックス時の点灯の修正は6/27に入れました。
なお、ゲージが点灯しないのは上限体力到達時に時間を止めてしまっているのが原因だと思います。
ゲージ側から逃げるシーン終了を管理するか、時間を止めるのを上限体力到達後ゲージ演出にかかる0.2秒を待ってからに変更してください。

**Comment by asterisk-cn** [comment]
@Iguchi-Keigo2000 
WaitForSecondsをWaitForSecondsRealtimeに変えると時間止まっても動きます
WaitForFixedUpdateは必要以上に更新かけてるからあまりよろしくない
