### ISSUE TITLE
SE・エフェクト

### ISSUE THREAD

**Issue by asterisk-cn** [asterisk-cn/BSGJ-E1#145]
- 合体りんご
  - 歩行 SE/エフェクト
- 魂
  - 歩行 SE
  - 被ダメ エフェクト
  - 着地時　エフェクト
- 障害物
  - 落ちる エフェクト
  - 落ちた時 SE（ナイフ以外）

_Originally posted by @asterisk-cn in https://github.com/asterisk-cn/BSGJ-E1/issues/73#issuecomment-2188168129_

**Comment by tky2302126** [comment]
魂合体時のエフェクトがついてないものがあったのでプレハブを編集
リンゴの歩行SEを追加　エフェクトを追加(40%)

**Comment by tky2302126** [comment]
リンゴの歩行エフェクトは現状だと軸がずれているので難しい
魂の着地エフェクトを追加
敵の攻撃時SEを再生指示を編集することで対応
