### ISSUE TITLE
コック体力調整

### ISSUE THREAD

**Issue by asterisk-cn** [asterisk-cn/BSGJ-E1#166]
> 現状
>   制限時間：10 s
>   体力：220
> 改善案（オーバーパワー！）
>   制限時間：30 s
>   体力（ジョイコン）：12000
>   体力（コントローラー）：500

体力を500に、ジョイコンの加速度→攻撃の変換割合を調整（現状から1/２４倍？）

**Comment by tsumikaze1318** [comment]
変換割合(_inputs.leftAttackValue / _conversionRate)で外から変更できるようにした。
変換割合追加したらJoycon使ってないとダメージが出ないのでUseJoyconがfalseの時ダメージを1固定 にした。
コックのHP500に設定にした。
