### ISSUE TITLE
攻撃のバリエーション

### ISSUE THREAD

**Issue by asterisk-cn** [asterisk-cn/BSGJ-E1#23]
EnemyAttackを継承
- 包丁（Knife）
- 鍋（Pot）
- のばし棒（Rod）
  - 転がる

参照
https://scrapbox.io/teamAbitsummit2024east/%E4%BB%95%E6%A7%98

**Comment by asterisk-cn** [comment]
優先度下げていいです

**Comment by tky2302126** [comment]
add:実装予定の攻撃クラスのダミースクリプト(Hand,Knife,Pod)を追加

**Comment by asterisk-cn** [comment]
包丁、鍋、台パンを作成
大きな挙動は変わらないから、EnemyAttackをつけたPrefabを作るだけでいいかも

**Comment by asterisk-cn** [comment]
追尾しないオブジェクトはランダムな位置に生成するように（ステージ内）

**Comment by tky2302126** [comment]
プルリクエストを出しました。

**Comment by asterisk-cn** [comment]
Handは攻撃後に上に上がってく仕様にするのでDestroyしないで大丈夫です

**Comment by asterisk-cn** [comment]
Handは上がりきったらDestroyする
