### ISSUE TITLE
キャラクターをCharacterControllerで動かす

### ISSUE THREAD

**Issue by asterisk-cn** [asterisk-cn/BSGJ-E1#27]
障害物がプレイヤーの移動を妨げるように仕様変更
Colliderで管理するよりCharacterControllerを使った方が便利（なはず）

## タスク
- 移動の処理をCharacterControllerで行う

**Comment by asterisk-cn** [comment]
https://docs.unity3d.com/ja/2019.4/Manual/class-CharacterController.html

**Comment by tky2302126** [comment]
PlayerCharacter.csにCharacterControllerを追加
追加に伴い、スクリプト内でCharacterControllerをアタッチ
PlayerCharacter.Moveを変更
移動方法の変更に伴い、RigidBodyをリムーブ

**Comment by asterisk-cn** [comment]
衝突判定でRigidBody使いたいから戻しておいて欲しい
Kinematicにして干渉はしないようにしたら正しく動くと思う

**Comment by asterisk-cn** [comment]
CharacteControllerのコンポーネントはコードの中じゃなくて事前につけておいて欲しいです（パラメータの調整とかをのちにすると思うので）
パラメータはデフォルトのままでいいです

**Comment by tky2302126** [comment]
CharacterControllerを追加しました
RigidBodyをRevertしました
