### ISSUE TITLE
3Dオブジェクトのインポート

### ISSUE THREAD

**Issue by asterisk-cn** [asterisk-cn/BSGJ-E1#40]

**Comment by asterisk-cn** [comment]
シーンに反映させたものをプルリクに投げて欲しいです
ブランチはdev/3Dでも新しく切ってもいいです

**Comment by asterisk-cn** [comment]
@tky2302126 
ゲーム画面でちゃんと見えるようにカメラの位置を変更してほしい！
あと、3Dオブジェクトはもともとあったスクリプトがアタッチされてるやつに入れる感じで！
例
Player
└りんごの3Dモデル

mainをマージして、攻撃のPrefabにも反映してほしい

**Comment by tky2302126** [comment]
カメラの位置を変更
Playerを対応

**Comment by asterisk-cn** [comment]
もともとスクリプトがついてる作ってあったオブジェクトに3Dモデルをくっつけるイメージに直す
（いままでのパラメータの変更を残したいので）
もともとのオブジェクトのメッシュ（MeshRenderer）は外しておいてもらえると助かります。

**Comment by tky2302126** [comment]
Player->Player1->3Dオブジェクトの階層で配置しました
まな板にBOXコライダーをつけてステージとしています。

**Comment by tky2302126** [comment]
#23 のHandのDestroyされないやつに対応しました
