### ISSUE TITLE
プレイヤー体力

### ISSUE THREAD

**Issue by asterisk-cn** [asterisk-cn/BSGJ-E1#42]
- 体力
  - 暫定3機
- 体力がなくなったらゲームオーバー

**Comment by tky2302126** [comment]
PlayerCore.csに_currentParameters.healthを減少する関数を追加
外部から呼び出されることを想定(EnemyAttackあたり？)
同関数にゲームオーバー処理として
MainGameManager.gamestateを変更する処理を追加
