### ISSUE TITLE
プレイヤー移動に慣性をつける

### ISSUE THREAD

**Issue by asterisk-cn** [asterisk-cn/BSGJ-E1#59]
パラメータ
　初速
　加速度
　慣性／減速度合い
を持たせて、移動に慣性をつける

**Comment by tsumikaze1318** [comment]
RigidBodyを使ってですか？それともCharacterControllerを使用してですか？

**Comment by asterisk-cn** [comment]
CharacterControllerを使って欲しい
現在速度をパラメータとして持たせる感じ

**Comment by asterisk-cn** [comment]
慣性用パラメータをCharacterParametersで管理するよう変更
velocityにy軸の速度は入れないように変更
