### ISSUE TITLE
魂攻撃ヒット時の仕様変更・シーン遷移用ゲージ

### ISSUE THREAD

**Issue by asterisk-cn** [asterisk-cn/BSGJ-E1#68]
- 落下中に魂へヒットした障害物は残る
- ファイトシーンへの遷移に必要なゲージが減少する（合体時よりは少なくする）
  - 魂拾ったら＋いくつかして、魂が攻撃喰らったらーいくつかするゲージ（float）に変更
  - UnionCountを上のゲージに置き換える

**Comment by tsumikaze1318** [comment]
プラスやマイナスにする値は後でInspector上から変更できるようにした方がいいですか？

**Comment by asterisk-cn** [comment]
プレイヤーに当たった場合は攻撃が消え、魂に当たった場合は変化なしにしてください

手は鈴木さんが直してくれることになっています

インスペクターで調整できるようにしておいた方が良さそうです

**Comment by tsumikaze1318** [comment]
マイナスの方はゲージの最大値を減らす感じでしたっけ？

**Comment by asterisk-cn** [comment]
増減は両方中の数字でいいと思います

**Comment by tsumikaze1318** [comment]
魂へヒットした場合残るようにしたがその場合2回攻撃判定がある。
値の増減を作ったが2回判定あるので増:2減:1にしても2回減る

**Comment by asterisk-cn** [comment]
衝突したらOnEnterCollisionを無効にするflagをもたせるとかかな？
ただ、魂と本体が同時ヒットする場合とか考えなきゃかも？
あとで聞いてみるか
