### ISSUE TITLE
敵攻撃の自動化

### ISSUE THREAD

**Issue by asterisk-cn** [asterisk-cn/BSGJ-E1#7]
### TODO
- 敵の攻撃がプレイヤーを追従するようにする
  - 攻撃中は横移動しない方が良さそう
- 攻撃を自動で行うようにする
  - とりあえずランダムでいいと思います

**Comment by asterisk-cn** [comment]
作業する時UnityVersionControlをRemoveしてくれると助かります

**Comment by asterisk-cn** [comment]
@tky2302126 
設計図の更新ができてなかったので更新しました
https://scrapbox.io/teamAbitsummit2024east/%E9%96%8B%E7%99%BA%E3%82%BF%E3%82%B9%E3%82%AF

**Comment by tky2302126** [comment]
開発のツリーにプッシュしました。
遅れてしまい申し訳ないです。

**Comment by asterisk-cn** [comment]
@tky2302126 
敵とプレイヤーの距離が近い時に敵がブルブルする挙動がみられるから、距離が移動量（moveSpeed）より小さいときは元の距離を移動するように変更したほうがよさそう

**Comment by tky2302126** [comment]
条件式を修正しました。
