### ISSUE TITLE
BGM・効果音

### ISSUE THREAD

**Issue by asterisk-cn** [asterisk-cn/BSGJ-E1#73]

**Comment by asterisk-cn** [comment]
音バグ
・包丁が落下する瞬間の音が連続でなってる
・フィニッシュブローが倒した後何回も鳴らせる
・メニュー画面での決定音が連続でなってる

**Comment by tky2302126** [comment]
包丁の連続音はプレイヤー１の歩行音だと思います。
アニメーションにキーを打って再生指示をしているのでアイドルモーションを
実装してから再度確認します。

**Comment by asterisk-cn** [comment]
- 合体りんご
  - 歩行 SE/エフェクト
- 魂
  - 歩行 SE
  - 被ダメ エフェクト
  - 着地時　エフェクト
- 障害物
  - 落ちる エフェクト
  - 落ちた時 SE（ナイフ以外）
- ファイトシーン
  - パンチヒット エフェクト （＋一回点滅）
