### ISSUE TITLE
アニメーション

### ISSUE THREAD

**Issue by asterisk-cn** [asterisk-cn/BSGJ-E1#88]

**Comment by asterisk-cn** [comment]
- リンゴのパンチ
  - 加速度に応じてアニメーション再生
- コックが倒れてく

**Comment by tsumikaze1318** [comment]
リンゴの攻撃した際にアニメーションの追加とシェフの被弾アニメーション、倒れるアニメーション追加しときました。
リンゴの方はswitchで試せてないのでそちら側でデバッグお願いします。
コックに関してはメソッドのDieをAnimationEventでやったのですが階層が別のため少しごり押し気味にやったので後で改良するかもしれないです。なんかいい方法あったらそちらで変えちゃってください。

**Comment by asterisk-cn** [comment]
要ジョイコンでのチェック
